### ISSUE TITLE
There's a bug

### ISSUE THREAD

**Issue by wwwlg** [liugangcode/data_centric_transfer#1]
When I run to this file: data_centric_transfer-main/utils/mol_utils.py (line109). The following problems can occur:   
         embeds += torch.mm(probs, embedding_list[raw_dim].weight)
      RuntimeError: mat1 and mat2 shapes cannot be multiplied (1330x4 and 5x300)
How should I modify it? Looking forward to your reply.

**Comment by liugangcode** [comment]
Hi, thank you for your question. I cannot reproduce the error using an arbitrary dataset. Could you provide more information about the dataset and any other relevant details? I also noticed that the error on line 109 differs slightly from the original code on line 94. Can you share some details about the modifications you made that might have caused the error?

**Comment by shijiale0609** [comment]
I had the same problem if I install the most updated ogb version, ogb==1.3.6

**Comment by liugangcode** [comment]
Thank you for the information. You can compare the difference between [line 9](https://github.com/snap-stanford/ogb/blob/325216676918480e0fa93e471207ab0e007af263/ogb/utils/features.py#L9) in ogb 1.3.4 and ogb [1.3.6](https://github.com/snap-stanford/ogb/blob/a47b716f7e972f666eae9909ee0f922cd0f9d966/ogb/utils/features.py#L9). These differences may cause the problem. I have closely examined the issue. Please let me know if it helps.
