### ISSUE TITLE
what is the normal output

### ISSUE THREAD

**Issue by shijiale0609** [liugangcode/data_centric_transfer#2]
what is the normal output if running the given command:
```
# OGBG-SIDER
python main.py --dataset ogbg-molsider
```
Here is my output. However, it keeps running.
<img width="985" alt="output" src="https://github.com/liugangcode/data_centric_transfer/assets/22111378/4595e7e5-d97c-4138-a0d0-aec2716aadb4">

**Comment by liugangcode** [comment]
You can change the configuration file by setting 'no_print' to 'False' to monitor the training progress; otherwise, it will only output the prediction results after training
