### ISSUE TITLE
Custom Molecule Dataset

### ISSUE THREAD

**Issue by xwang112358** [liugangcode/data_centric_transfer#3]
Thank you for the great work. 

If I want to apply your framework to a custom molecular dataset that requires transformation from the SMILES strings to PyG data, what do I need to mind? 

I think GDSS trained on QM9 can generate molecules with no more than 9 atoms, and there are only 5 types of atoms and 3 kinds of bonds represented by one-hot encoding vectors. However, I find the ogb-molbace dataset has 9 atom features. How do you connect the gap between the OGB dataset and pre-trained GDSS? Please correct me if I am wrong.

Many Thanks,
Allen Wang

**Comment by liugangcode** [comment]
Hi Allen,

Details on converting SMILES to PyG objects can be found in [line 85 here](https://github.com/liugangcode/data_centric_transfer/blob/73785c584e4d5a90c2034afb1e001257a3d347bb/dataset/data_utils.py#L85). You may adapt this function to read your SMILES data.

Details on addressing the gap between atom types can be found [here](https://github.com/liugangcode/data_centric_transfer/blob/73785c584e4d5a90c2034afb1e001257a3d347bb/utils/mol_utils.py#L145), where we use a variable `enable_mask` to control the diffusion process on only the pre-trained atom types (i.e., CNOF for QM9).

**Comment by xwang112358** [comment]
Hi Gang, I have a naive question about reproducing the GIN results in Table 2. I only disabled the condition statement at line 165 of main.py, but the output results are significantly higher than the ones reported in the paper. For example, these are the results of two datasets from 5 trials of experiments

Ogbg-Molbace: 
GIN: 0.8273+-0.0401
DCT: 0.8286+-0.0377 

Ogbg-molbbbp
GIN: 0.6953+-0.0155
DCT: 0.6927+-0.0186

While I could reproduce DCT results in the paper, I have no idea how to get the GIN results correctly. Could you give me some guidance? 

Best,
Allen Wang

**Comment by liugangcode** [comment]
Hi, we use the GIN code from OGB and you can follow the guidance here: https://github.com/snap-stanford/ogb/tree/master/examples/graphproppred/mol

**Comment by xwang38438** [comment]
Thank you very much for the hint! Also in paper D.2, you tested the chemical validity of the generated graph in different downstream tasks. I wonder if you can guide me to the source code that converts the graph back to the molecule.
